apiVersion: infra.whiz.ai/v1
kind: AIGen
metadata:
  name: aigen
spec:
  targetNamespace: test

  llmDeployment:
    name: ai-llm
    replicas: 1
    requiredGpuMemoryGB: 80

  textProcessingDeployment:
    cpuDeployment: ai-text-processing-cpu
    gpuDeployment: ai-text-processing-gpu
    replicas: 1
    requiredGpuMemoryGB: 40